### ISSUE TITLE
Bug with resetConnection() call in connect()

### ISSUE THREAD

**Issue by chris-anstey-runware** [Runware/sdk-js#9]
After trying out a fix for #8, I found an issue with the `connect()` code, and the call to `resetConnection()`. When trying to reconnect, the code would error with this: 
```
Error: WebSocket was closed before the connection was established
    at WebSocket.terminate (.../js/node-demo/node_modules/ws/lib/websocket.js:489:7)
    at RunwareServer.resetConnection (.../js/node-demo/node_modules/@runware/sdk-js/dist/index.js:1319:18)
    at RunwareServer.connect (.../js/node-demo/node_modules/@runware/sdk-js/dist/index.js:1356:10)
    at Timeout._onTimeout (.../js/node-demo/node_modules/@runware/sdk-js/dist/index.js:1206:24)
```
It looks like [here](https://github.com/Runware/sdk-js/blob/b28f3f386d8cee4d83a50df24e10ff0a5058601a/Runware/Runware-server.ts#L132), we should also check the WebSocket `readyState` before calling `terminate()` and `close()`, eg:
```
    this.resetConnection = () => {
      if (this._ws) {
        this._listeners.forEach((list) => {
          var _a;
          (_a = list == null ? void 0 : list.destroy) == null ? void 0 : _a.call(list);
        });
        this._ws.removeAllListeners();
        if (this._ws.readyState === 1) {
          this._ws.terminate();
          this._ws.close();
        }
        this._ws = null;
        this._listeners = [];
      }
    };
```

**Comment by gorantosicpf** [comment]
the fix is here: https://github.com/Runware/sdk-js/pull/11
